### ISSUE TITLE
Terminating setInterval handle during testing

### ISSUE THREAD

**Issue by avatarneil** [plantain-00/ws-heartbeat#4]
## Observed behavior
I'm currently using this library in a project, and have run into some trouble cleaning things up during my test suite.
It seems like the `setInterval` handle is not being terminated upon closing the websocket server `ws.close()`, and there doesn't seem to be a kill-switch exposed by this library to handle manual termination.

## Ideal behavior
Option 1) Listening for the websocket server's `close` event, and terminating the handle as a result of that.
Option 2) Returning the `setInterval` function to the caller of `setWsHeartbeat`, such that a caller can manually execute `clearInterval(/* return value from setWsHeartbeat */)`

I'm more than happy to cut a PR implementing either of these approaches! I did a quick copy-pasta of the `setWsHeartbeat` function from this library and implemented option 1 in my codebase, and all seems well. 

## Current workaround
The project previously used Mocha and I observed this behavior, and am now observing it in Jest as well; to remedy, I've been using `--exit` (for mocha) and `--forceExit` (for jest) to kill all handles at the end of the suite, but this is generally fairly discouraged, as open handles are typically indicative of real bugs.

**Comment by plantain-00** [comment]
PR is welcome
