### ISSUE TITLE
Dependency: Update package dependency of ws to v8 or above (v7 to v8+)

### ISSUE THREAD

**Issue by tfrancois** [plantain-00/ws-heartbeat#6]
In the package.json for this library, the lone package dependency is listed as:

`"ws": "7"`

Can it be updated simply to:

`"ws": "^8.18.0"`

I am using the latest version of `ws` with this nifty library with v8 in multiple projects with no issue, and I am keen on keeping my package bundle small by eliminating duplicate dependencies and/or mixed versions and because the specified dependency has not been updated I cannot remove the nested package requirement due to this issue.  Can we please make this quick fix?

**Comment by plantain-00** [comment]
It should be in v1.3.0 now.

**Comment by tfrancois** [comment]
Thank you so much @plantain-00 for such a quick response and resolution!
